### ISSUE TITLE
Allow user to create common website directory

### ISSUE THREAD

**Issue by jbrinkman** [nvisionative/nvQuickSite#107]
As a user, I want to be able to setup a common directory location that is used for all the sites I create.  This location would be the starting point for new sites, although I could still override this by using the location folder picker on the Site Info screen.  It would also be nice if the system combined this directory with the website name to suggest a folder (i.e. if the website is xyz.dnndev.me, and the common directory is c:\websites, then it would suggest c:\websites\xyz as the location).  These features would minimize the effort to create a new site since in most cases the defaults would be sufficient.

**Comment by nvisionative** [comment]
Thank you for the suggestion @jbrinkman - we are interested in hearing what others think of this. In initial interviews we conducted, everyone preferred to just have the app remember their last used folder location, since many of them utilize a specific naming convention (that is sometimes not based on the site name). We are open to making this change, but would like to vet the idea a bit.

**Comment by jbrinkman** [comment]
Why would a user keep creating a website in the same folder?  In my dev environment, I have dozens of sites setup.  They might all share a common root folder, but each site is built in it's own sub-folder under that root.

**Comment by nvisionative** [comment]
We don't believe they would keep creating a website in the same folder.  However, it is a common practice in desktop apps for it to remember the last location selected so that one does not have to re-navigate to their desired location.  What if the app just remembers one level up from the last selected install location?  Would that help?

**Comment by jbrinkman** [comment]
Yes.  Effectively that would be the root folder for most of my sites.

**Comment by nvisionative** [comment]
@jbrinkman - at minimum I think we can plan for that change.  If others want the full suggested change, we can make that as well.  Or perhaps we can look into adding a setting in for user preferred handling.

**Comment by hismightiness** [comment]
Personally, the way it works now is great for me.  I don't necessarily use the same folder over and over, but I do sometimes - especially when testing things or doing POC's.  Since everything is pretty much in same area for me, changing the folder is only an additional click away... but I'm just one user.  I hope others chime in on this too.

**Comment by nvisionative** [comment]
Thanks to the video posted in another issue by @jbrinkman - [http://screencast.com/t/8jfbAdbYE](http://screencast.com/t/8jfbAdbYE) - I believe we have an idea now on how to best handle this.  We'll go ahead and assign the issue and keep you posted on progress.  We are planning for another release soon.
