### ISSUE TITLE
Windows Defender warning & unable to install new version over old version

### ISSUE THREAD

**Issue by jncraig** [nvisionative/nvQuickSite#162]
Windows Defender warns me about installing.

Won't install over existing earlier version.  

---------
It would be nice if at least the second of these didn't happen.

**Comment by nvisionative** [comment]
@jncraig thank you for reporting this.  It is unfortunately a limitation of this technology stack.  We are looking into building a new installer based on [WiX Toolset](http://wixtoolset.org/).  See #150

**Comment by jncraig** [comment]
Yeah, as I said ... not exactly issues but time wasters.  <g>  And the
first one could scare people away.

**Comment by nvisionative** [comment]
We agree @jncraig - just the way this old tech works unfortunately.  Hopefully we'll be able to mitigate in the future with a new installer per #150.

**Comment by hismightiness** [comment]
I have the same issues...  

Is the intended user experience right now to uninstall the previous version and then install the new one?  Are there any data/preferences that we lose?

![2018-03-07_1026](https://user-images.githubusercontent.com/938023/37110595-348a9e68-21f2-11e8-984e-00cb59710fe7.png)

**Comment by hismightiness** [comment]
On a side note, here's my experience after uninstalling and installing the new 1.2 version.

* The taskbar icon/shortcut isn't removed and the icon is unchanged upon uninstall (if you did this to begin with)
* When you install the new version, the taskbar icon is now a generic paper-looking icon and the path is the same
* In order to restore the icon to its original state, you need to right-click three times to pin, unpin, and then pin again

(I realize much or maybe even all of this is likely unrelated to the app itself)

**Comment by hismightiness** [comment]
Oh, and some of the preferences are indeed missing when you uninstall and install over again.  This includes the installation location, domain suffix, and database server name.

**Comment by nvisionative** [comment]
Thanks @hismightiness for the additional information.  We are aware of all of this and as stated, it is unfortunately a side-effect of this archaic installer.  We hope all of these issues will be resolved when we make the switch to a new installer per issue #150.  Thanks again for the interest in making this a better user experience for everyone!

**Comment by abukres** [comment]
@nvisionative What software are you using for the installer?

**Comment by nvisionative** [comment]
@abukres unfortunately it is using the built-in Windows Installer (Setup Project in VS).  We have plans to convert it all to WIX but just haven't had the time to invest yet.

**Comment by abukres** [comment]
@hismightiness ClickOnce does the same thing. It asks the user to uninstall the old version first. Maybe it's Microsoft's way to make sure the user actually wants to install the new version.
As for the preferences issue, nvQuickSite can create a folder under ProgramData for example and store the preferences in it. Uninstallation shouldn't touch it because the installer doesn't know about it.

**Comment by nvisionative** [comment]
We are performing some clean up of stale issues and will be closing this one.  This will eventually be addressed when a new installer is built to replace this antiquated one.  :)  Feel free to re-open this issue if necessary.
