### ISSUE TITLE
Desktop Notifications

### ISSUE THREAD

**Issue by hismightiness** [nvisionative/nvQuickSite#174]
Add desktop notifications for:

- New release of nvQuickSite/nvQuick[name]
- New DNN release
- New DNN RC release
- Warning for pull request window closing
- Warning for end of the RC testing window

This can be turned off, but it's on by default.

**Comment by nvisionative** [comment]
This would be a substantial effort and we would need to scope this very clearly in order to understand exactly what we want to happen, etc.

**Comment by abukres** [comment]
Does Github provide an api for releases? nvQuickSite can make a call to iy and get the latest release version.

**Comment by nvisionative** [comment]
@abukres yes, GitHub has an API for releases.  That is a good option for detecting new releases for sure, and exactly what I already had in mind.  However, that is not the more complex part.  The more complex part is desktop notifications, specifically using the Win10 ToastNotifications from this WinForms app.  This is much more simple via UWP apps, but I haven't had time to research a WinForms solution yet.  Once that nut is cracked, we can probably move forward with this implementation.

**Comment by nvisionative** [comment]
@abukres - that is partly what I am talking about.  Having a background task scheduled to poll for updates is one idea that could be explored more for sure.  However, I was specifically referring to Win10 ToastNotifications from a WinForms app.  I’m not sure how easy or possible that will be.  Again, I haven’t had time to research this fully.  Any help would be greatly appreciated!

**Comment by abukres** [comment]
@nvisionative I am trying to understand what you want. If you want a polling task app, then it's another .exe running independently of nvQuickSite. You mentioned WinForms and Windows 10. The task app shouldn't be dependent on Windows 10 API. There are users who are still on Windows 7. All the app is doing is polling an API end point and showing a toast. There are nuget toast packages and I think there are task app packages. We just have to use one and make it poll and show a toast. Nothing dependent on Windows 10 or being a Winform app. There's no UI.

**Comment by nvisionative** [comment]
@abukres at this point in time I personally am not "wanting" anything particular.  I was simply trying to bring to light that what we use for notifications will need to be figured out.  I have yet to do that. 
 😉  

One option is to leverage Win10 ToastNotifications (see [THIS](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop) for more information).  However, as you have pointed out, not everyone is on Win10.  Excellent point and I'd like to support those people not on Win10.  If you have ideas on some potential solutions, I am certainly open to them.

Regarding a polling task app versus just performing checks in the current app, I think a good start would be to build it into the existing nvQuickSite app.  What are your thoughts?

**Comment by abukres** [comment]
@nvisionative The notifier will look at the latest version on Github or your PackageManifest.xml file. What is the local thing that it is comparing against to determine the existence of a new version? The version number from the last poll?

**Comment by nvisionative** [comment]
@abukres there are many ideas in consideration here (see original post).  nvQuickSite already has a check for whether or not there is a new release available.  It does not show up in the form of a notification, but rather on the UI itself (see [THIS ISSUE](https://github.com/nvisionative/nvQuickSite/issues/151)).  So, we need to have a conversation around each proposed notification recommendation by @hismightiness in order to make sure we are clear about any proposed approaches.

**Comment by abukres** [comment]
@nvisionative Your PackageManifest.xml or another end point can supply all the information above. How you plan to enter this information in your database is up to you. You're either up to date with the information as they come out and you update your database manually or have a little data entry web page where one who has access to it can enter it for you. I assume there are other options.
I don't know if Github API has support for custom properties defined by the user which an app can poll.

This would be a lot more useful in a system tray app. Most people don't have nvQuickSite running all the time so putting this functionality in there is limiting. Maybe you want to create another repo for this app since it's independent of nvQuickSite.

**Comment by nvisionative** [comment]
@abukres I am in agreement with you.  This needs to be a separate app altogether.  nvQuickSite is designed to only be running while you are installing DNN - period.  

I have a great idea for how this can be done as a separate app.  If you want to collaborate on it, that would be awesome.  Send me an email via the contact for on our website (https://www.nvisionative.com) and I’ll share my ideas.  Then I can spin up a repo to get started.

**Comment by nvisionative** [comment]
@hismightiness I am going to close this issue.  These ideas are being considered for enhancements to [nvQuickPulse](https://github.com/nvisionative/nvQuickPulse) mobile app and potentially a new nvQuickPulse desktop app.  
🙌 😃 🥇
