### ISSUE TITLE
Retain settings/preferences on upgrade

### ISSUE THREAD

**Issue by hismightiness** [nvisionative/nvQuickSite#224]
Currently, when you upgrade from one version of nvQuickSite to the next, your primary preferences/settings are overwritten.  This includes the SQL Server name, domain name, local file system folder, and more.

This update proposes that when you upgrade, all of the standard user-facing settings/preferences are retained and carried over to the upgraded instance of nvQuickSite.  

As is currently stands, the first time using nvQuickSite after upgrade, all of these settings/preferences are completely wiped out, as if you installed nvQuickSite for the first time.  For less technical users, this behavior makes it more difficult to use (e.g., entry-level QA testers).  They may have to find someone to help them figure out their settings again.

The advanced settings (e.g., Release Candidate) maybe should be reset though, to ensure that people are intentional about the RC installation process.  

Any discussion/thoughts on this proposed update are all welcome.  :)

**Comment by nvisionative** [comment]
@hismightiness thanks for documenting this.  I agree it should work this way.  I am not sure if the standard installer we currently use has an option for this or not.  It is worth investigating and that project is now a part of the repo.  If anyone has time to delve into this, any help would be greatly appreciated.  Otherwise, we'll put this into the queue here and get to it when possible.

Ultimately we have plans to replace the archaic installer with a more modern installer like the [WIX TOOLSET](http://wixtoolset.org/).  See #150

**Comment by nvisionative** [comment]
@hismightiness I think I may have found a [solution to this issue on StackOverflow](https://stackoverflow.com/questions/23924183/keep-users-settings-after-altering-assembly-file-version).  I wanted to document it here for quick reference during the creation of a pull request.  😃
