### ISSUE TITLE
Add support for Max File Upload Size Setting

### ISSUE THREAD

**Issue by mbuelsing** [nvisionative/nvQuickSite#319]
Would it be possible (and desirable) to add the ability to increase the max file upload size to the nvQuickSite App?

I am approaching it from the viewpoint of a user trying to get up and running quickly. One of the things that I need to change on a new site most of the time is the upload file size limit. This is a very manual task that follows right after the easy, push-button experience of nvQuickSite.  I just had that experience and I thought, wouldn't it be great if it were part of the app? If that were an option in nvQuickSite, I would use it and it would save time. FWIW.

**Comment by david-poindexter** [comment]
Pretty much anything is possible.  The bigger question is "should it be there?"  My vote would be no because **nvQuickSite** is an "installer", not a "configuration tool".

If we put this feature in there, that could then lead to much more similar features, most likely based on things you can do via `web.config`.  Things like this are ways to quickly get to feature bloat.  I've seen it over and over with other apps.

I am certainly not trying to shoot down the idea.  😉   This is "our app".  It is open-source, by and for the community.  Therefore, it is worthy of dialog with the broader community to see if there is interest.  Those were just my gut reaction thoughts.  I'd like to hear what others say and to see what the proposed solution would actually be.  Then we can make a determination from there and see if anyone is willing to contribute the solution to the project.

**Comment by mitchelsellers** [comment]
Personally, I strongly oppose editing this setting to anything larger than DNN defaults unless you have a specific and regular reason to make the change.

There are security implications of having this value set large, and the current DNN default value is already larger than traditionally recommended.

**Comment by david-poindexter** [comment]
Thanks @mitchelsellers - I totally agree with you regarding these "best practices".  I think this is more about the option to change the setting rather than what should/shouldn't be used on a production website.  

As a reminder to everyone, the intended use for this tool is for local development purposes only.  It is not recommended for use on a production server (though I realize many people do).  Thus my stance on this new feature request.  I think it further "enables" people to use this tool in production environments.  I'd prefer to keep the scope of this tool to local development use and keep it focused on it's primary job - installing DNN quickly.  Configuration of DNN is a whole different realm.  😉

**Comment by hismightiness** [comment]
I think a better solution for this is for individuals who (hopefully) know the impacts of things like this can pre-update their web.config and site template files in the installation package themselves to do things like this.
