### ISSUE TITLE
Set Folder Permissions Error

### ISSUE THREAD

**Issue by skarpik** [nvisionative/nvQuickSite#347]
I have been using nvQuickSite v.2.1.1.0 on Windows 10 Pro with  SqlExpress v13.0.1742. - everything works perfectly.

I am migrating to a new computer with Windows 11 Pro and SqlExpress v15.0.2080. Unfortunately, nvQuickSite fails for both v2.1.1.0 and 2.1.2.0 (error messages are attached).

For both computers, the websites are being installed on the D:\ drive (the C:\ drive is a smallish SSD).

Access rights for D:\Websites folder on the Windows 10 and Windows 11 computers are identical.

I note that for v2.1.2.0, the error message refers to "NT Service\MSSQLSERVER" rather than "NT Service\MSSQL$SQLEXPRESS" which I would expect.

Maybe Windows 11 is handling some file access rights differently than Windows 10.

**Error for version 2.1.1.0**

![nvquicksite v2 1 1 0](https://user-images.githubusercontent.com/3846223/143506473-a392e7e4-28c3-4a8a-bbce-2ba229a7caec.jpg)

**Error for version 2.1.2.0**

![nvquicksite v2 1 2 0](https://user-images.githubusercontent.com/3846223/143506508-67084238-2374-419a-9c30-8f30fef32f1d.jpg)

**Comment by david-poindexter** [comment]
@skarpik can you enable verbose logging and see if that provides more insight?  I am using it on Windows 11 just fine, but not on a separate partition and not SQL Express.  If you have a named instance, then you won't be able to use "(local)".  Not sure if that is an issue or not, but thought I'd mention it.

**Comment by skarpik** [comment]
Mystery solved. For my SQL server, I had the name (local)\SQLEXPRESS (and nvQuickSite fails). However, if I use the name OMEN2\SQLEXPRESS where OMEN2 is the machine name, then everything works perfectly. Thanks.

**Comment by david-poindexter** [comment]
Awesome @skarpik - we could probably do a bit better in the app to provide in-context help for stuff like this.

**Comment by WillStrohl** [comment]
Ugh... This is happening to me too on Windows 11.  It never happened before.  I also had to change the server name.  I've tried the original `(local)` that was already there and in use since I first installed nvQuickSite.  I also tried the other common version of this where `.` also means `(local)` and `(localhost)`.  Non-technical people will not figure this out easily and technical people may not know to search for this closed issue.  

I think longer-term, it may be a good idea to attempt to switch the machine name for the end-user, if the host machine is Windows 11.  

![image](https://user-images.githubusercontent.com/938023/145117183-4d940a5d-39cb-44ee-b11e-49b046a2d5d6.png)
